Cosmetic changes
SmartPool/SmartPool.github.io pull request #8
Opened 2017-01-16 22:14 UTC by yaronvel

1. Added links to block explorers for each account.
2. Removed annoying animation when displaying the donations sum.

2017-01-16 23:28 UTC, tranvictor requested changes

2017-01-16 23:28 UTC, tranvictor commented on donate.slim
> +                p.address <a href=#{smart_pool_ethereum_url}>#{smart_pool_address}</a>
I think we should better eliminate pure HTML in slim, it's shorter
```
p.address
  a href="#{smart_pool_ethereum_url}" #{smart_pool_address}
```

2017-01-16 23:28 UTC, tranvictor commented on index.slim
> +              p.progress#total-fund-raised.total-fund-raised 0.00
We can also remove corresponding javascript and stylesheet files to odometer if we want to remove animation.

2017-01-16 23:51 UTC, tranvictor commented on donate.slim
> +                p.progress#total-fund-raised.total-fund-raised 0.00
Should we also change the `0.00` to `loading...` or some sort?

2017-01-16 23:52 UTC, tranvictor commented on index.html
>                  0.00
Change `0.00` to `loading...` here too?

2017-01-17 19:03 UTC, yaronvel commented on donate.slim
> +                p.address <a href=#{smart_pool_ethereum_url}>#{smart_pool_address}</a>
It doesn't work.
I get
```
Ethereum: a href="https://etherscan.io/address/0x98F62d8aD5a884C8bbcf262591DFF55DAb263B80" 0x98F62d8aD5a884C8bbcf262591DFF55DAb263B80
``` 
in the webpage.

2017-01-18 04:18 UTC, tranvictor approved these changes

2017-01-18 04:25 UTC, merged